import:
	cp ./k8s.io/api/admission/v1beta1/generated.pb.swift ./protos/admissionV1Beta1.pb.swift
	cp ./k8s.io/api/admissionregistration/v1beta1/generated.pb.swift ./protos/admissionregistrationV1Beta1.pb.swift
	cp ./k8s.io/api/apps/v1/generated.pb.swift ./protos/appsV1.pb.swift
	cp ./k8s.io/api/apps/v1beta1/generated.pb.swift ./protos/appsV1Beta1.pb.swift
	cp ./k8s.io/api/apps/v1beta2/generated.pb.swift ./protos/appsV1Beta2.pb.swift
	cp ./k8s.io/api/authentication/v1/generated.pb.swift ./protos/authenticationV1.pb.swift
	cp ./k8s.io/api/authentication/v1beta1/generated.pb.swift ./protos/authenticationV1Beta1.pb.swift
	cp ./k8s.io/api/authorization/v1/generated.pb.swift ./protos/authorizationV1.pb.swift
	cp ./k8s.io/api/authorization/v1beta1/generated.pb.swift ./protos/authorizationV1Beta1.pb.swift
	cp ./k8s.io/api/autoscaling/v1/generated.pb.swift ./protos/autoscalingV1.pb.swift
	cp ./k8s.io/api/autoscaling/v2beta1/generated.pb.swift ./protos/autoscalingV2Beta1.pb.swift
	cp ./k8s.io/api/autoscaling/v2beta2/generated.pb.swift ./protos/autoscalingV2Beta2.pb.swift
	cp ./k8s.io/api/batch/v1/generated.pb.swift ./protos/batchV1.pb.swift
	cp ./k8s.io/api/batch/v1beta1/generated.pb.swift ./protos/batchV1Beta1.pb.swift
	cp ./k8s.io/api/batch/v2alpha1/generated.pb.swift ./protos/batchV2Alpha1.pb.swift
	cp ./k8s.io/api/certificates/v1beta1/generated.pb.swift ./protos/certificatesV1Beta1.pb.swift
	cp ./k8s.io/api/core/v1/generated.pb.swift ./protos/coreV1.pb.swift
	cp ./k8s.io/api/extensions/v1beta1/generated.pb.swift ./protos/extensionsV1Beta1.pb.swift
	cp ./k8s.io/api/imagepolicy/v1alpha1/generated.pb.swift ./protos/imagepolicyV1Alpha1.pb.swift
	cp ./k8s.io/api/networking/v1/generated.pb.swift ./protos/networkingV1.pb.swift
	cp ./k8s.io/api/policy/v1beta1/generated.pb.swift ./protos/policyV1Beta1.pb.swift
	cp ./k8s.io/api/rbac/v1/generated.pb.swift ./protos/rbacV1.pb.swift
	cp ./k8s.io/api/rbac/v1alpha1/generated.pb.swift ./protos/rbacV1Alpha1.pb.swift
	cp ./k8s.io/api/rbac/v1beta1/generated.pb.swift ./protos/rbacV1Beta1.pb.swift
	cp ./k8s.io/api/scheduling/v1alpha1/generated.pb.swift ./protos/schedulingV1Alpha1.pb.swift
	cp ./k8s.io/api/settings/v1alpha1/generated.pb.swift ./protos/settingsV1Alpha1.pb.swift
	cp ./k8s.io/api/storage/v1/generated.pb.swift ./protos/storageV1.pb.swift
	cp ./k8s.io/api/storage/v1beta1/generated.pb.swift ./protos/storageV1Beta1.pb.swift
	cp ./k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.swift ./protos/apiextensionsV1Beta1.pb.swift
	cp ./k8s.io/apimachinery/pkg/api/resource/generated.pb.swift ./protos/apimachineryResource.pb.swift
	cp ./k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.swift ./protos/apimachineryMetaV1.pb.swift
	cp ./k8s.io/apimachinery/pkg/runtime/schema/generated.pb.swift ./protos/apimachineryRuntimeSchema.pb.swift
	cp ./k8s.io/apimachinery/pkg/runtime/generated.pb.swift ./protos/apimachineryRuntime.pb.swift
	cp ./k8s.io/apimachinery/pkg/runtime/generated.pb.swift ./protos/apimachineryRuntime.pb.swift
	cp ./k8s.io/apimachinery/pkg/util/intstr/generated.pb.swift ./protos/apimachineryUtilIntstr.pb.swift

sync-protos:
	cp protos/*.pb.swift Sources/K8s